---
- hosts: web_servers
  become: true
  tasks: 
     
  # - name: isntall nginx on Ubuntu
        # apt: 
        # update_cache: yes
          # name: 
          # - nginx
              #          state: latest
      
      - name: start nginx.service
        service: 
          name: nginx.service 
          state: started 
       

      - name: Copy file 
        copy: 
          src: Javad_html.html 
          dest: /var/www/html/index.nginx-debian.html
          owner: root
          group: root
          mode: 0644
       
