---

- hosts: web_servers 
  become: true
  tasks: 
  
  
  - name: install apache2 package
    apt: 
      update_cache: yes 
      name: 
        - apache2
        - htop 
      state: latest
      #update_cache: yes 

      #  - name: add php support for apache
      # apt:
      # name: libapache2-mod-php 
